set_property PACKAGE_PIN W5 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property PACKAGE_PIN G2 [get_ports buzzer]
set_property PACKAGE_PIN R2 [get_ports EN]
set_property IOSTANDARD LVCMOS33 [get_ports EN]