set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state_wire[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state_wire[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {substate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {substate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U2 [get_ports {AN[3]}]
set_property PACKAGE_PIN U4 [get_ports {AN[2]}]
set_property PACKAGE_PIN V4 [get_ports {AN[1]}]
set_property PACKAGE_PIN W4 [get_ports {AN[0]}]
set_property PACKAGE_PIN W3 [get_ports {bcd_input[3]}]
set_property PACKAGE_PIN V3 [get_ports {bcd_input[2]}]
set_property PACKAGE_PIN V13 [get_ports {bcd_input[1]}]
set_property PACKAGE_PIN V14 [get_ports {bcd_input[0]}]
set_property PACKAGE_PIN B16 [get_ports {col[3]}]
set_property PACKAGE_PIN B15 [get_ports {col[2]}]
set_property PACKAGE_PIN A16 [get_ports {col[1]}]
set_property PACKAGE_PIN A14 [get_ports {col[0]}]
set_property PACKAGE_PIN L1 [get_ports {current_state_wire[1]}]
set_property PACKAGE_PIN P1 [get_ports {current_state_wire[0]}]
set_property PACKAGE_PIN A15 [get_ports {row[3]}]
set_property PACKAGE_PIN A17 [get_ports {row[2]}]
set_property PACKAGE_PIN C15 [get_ports {row[1]}]
set_property PACKAGE_PIN C16 [get_ports {row[0]}]
set_property PACKAGE_PIN W7 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]
set_property PACKAGE_PIN N3 [get_ports {substate[1]}]
set_property PACKAGE_PIN P3 [get_ports {substate[0]}]
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property PACKAGE_PIN R2 [get_ports rst]


set_property IOSTANDARD LVCMOS33 [get_ports waiting_state]
set_property PACKAGE_PIN U16 [get_ports waiting_state]
set_property IOSTANDARD LVCMOS33 [get_ports waiting_over]
set_property PACKAGE_PIN E19 [get_ports waiting_over]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property PACKAGE_PIN G2 [get_ports buzzer]
# set_property IOSTANDARD LVCMOS33 [get_ports {bcd0_reg[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {bcd0_reg[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {bcd0_reg[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {bcd0_reg[0]}]
# set_property PACKAGE_PIN W18 [get_ports {bcd0_reg[3]}]
# set_property PACKAGE_PIN V19 [get_ports {bcd0_reg[2]}]
# set_property PACKAGE_PIN E19 [get_ports {bcd0_reg[1]}]
# set_property PACKAGE_PIN U16 [get_ports {bcd0_reg[0]}]
