# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Adder_1/Adder_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1 || ORIG_REF_NAME==Adder_1} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_xor2_0_0/Adder_1_xup_xor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_xor2_0_0 || ORIG_REF_NAME==Adder_1_xup_xor2_0_0} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_xor2_0_1/Adder_1_xup_xor2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_xor2_0_1 || ORIG_REF_NAME==Adder_1_xup_xor2_0_1} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_nor2_0_0/Adder_1_xup_nor2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_nor2_0_0 || ORIG_REF_NAME==Adder_1_xup_nor2_0_0} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_nor2_0_1/Adder_1_xup_nor2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_nor2_0_1 || ORIG_REF_NAME==Adder_1_xup_nor2_0_1} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_nor2_0_2/Adder_1_xup_nor2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_nor2_0_2 || ORIG_REF_NAME==Adder_1_xup_nor2_0_2} -quiet] -quiet

# IP: bd/Adder_1/ip/Adder_1_xup_nor3_0_0/Adder_1_xup_nor3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_1_xup_nor3_0_0 || ORIG_REF_NAME==Adder_1_xup_nor3_0_0} -quiet] -quiet

# XDC: c:/Users/weibc/Desktop/EDA_1/EDA_1.gen/sources_1/bd/Adder_1/Adder_1_ooc.xdc
