#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : Calculator_total.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Nov 20 14:23:31 +0800 2021
# SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
#
# Copyright 1986-2021 Xilinx, Inc. All Rights Reserved. 
#
# usage: Calculator_total.sh [-help]
# usage: Calculator_total.sh [-lib_map_path]
# usage: Calculator_total.sh [-noclean_files]
# usage: Calculator_total.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Calculator_total.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64"

# Set vhdlan compile options
vhdlan_opts="-full64"

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xlconstant_v1_1_7 xil_defaultlib xlslice_v1_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Calculator_total.sh - Script generated by export_simulation (Vivado v2021.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k \
    "$ref_dir/../../../../EDA1.gen/sources_1/bd/Calculator_total/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlconstant_0_4/sim/Calculator_total_xlconstant_0_4.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlconstant_1_0/sim/Calculator_total_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k \
    "$ref_dir/../../../../EDA1.gen/sources_1/bd/Calculator_total/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlslice_0_0/sim/Calculator_total_xlslice_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlslice_0_1/sim/Calculator_total_xlslice_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlslice_2_0/sim/Calculator_total_xlslice_2_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xlslice_3_0/sim/Calculator_total_xlslice_3_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ipshared/e3e7/xup_inv.srcs/sources_1/new/xup_inv.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xup_inv_7_0/sim/Calculator_total_xup_inv_7_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xup_inv_7_1/sim/Calculator_total_xup_inv_7_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xup_inv_8_0/sim/Calculator_total_xup_inv_8_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_xup_inv_9_0/sim/Calculator_total_xup_inv_9_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_clock_divider_0_0/sim/Calculator_total_clock_divider_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_ring_counter_0_0/sim/Calculator_total_ring_counter_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_inv_0_3/sim/binary_2_segment_xup_inv_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_inv_1_0/sim/binary_2_segment_xup_inv_1_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/ipshared/778c/xup_and2.srcs/sources_1/new/xup_and2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and2_0_2/sim/binary_2_segment_xup_and2_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/ipshared/b79c/xup_and3.srcs/sources_1/new/xup_and3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and3_0_2/sim/binary_2_segment_xup_and3_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_inv_2_0/sim/binary_2_segment_xup_inv_2_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and2_1_2/sim/binary_2_segment_xup_and2_1_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and2_2_0/sim/binary_2_segment_xup_and2_2_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and2_3_1/sim/binary_2_segment_xup_and2_3_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and2_4_0/sim/binary_2_segment_xup_and2_4_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/ipshared/1ec9/xup_or2.srcs/sources_1/new/xup_or2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_or2_0_2/sim/binary_2_segment_xup_or2_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_or2_1_1/sim/binary_2_segment_xup_or2_1_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_or2_2_0/sim/binary_2_segment_xup_or2_2_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_xup_and3_1_0/sim/binary_2_segment_xup_and3_1_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_inv_0_0/sim/display_select_xup_inv_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_inv_0_1/sim/display_select_xup_inv_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_inv_0_2/sim/display_select_xup_inv_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_inv_0_3/sim/display_select_xup_inv_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_and2_0_0/sim/display_select_xup_and2_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_and2_0_1/sim/display_select_xup_and2_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_and2_0_2/sim/display_select_xup_and2_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_and2_0_3/sim/display_select_xup_and2_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/ipshared/1eaf/xup_or4.srcs/sources_1/new/xup_or4.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/src/display_select_xup_or4_0_0/sim/display_select_xup_or4_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/ipshared/5143/sim/display_select.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_0_6/sim/binary_2_segment_display_select_0_6.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_1_2/sim/binary_2_segment_display_select_1_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_2_0/sim/binary_2_segment_display_select_2_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_3_0/sim/binary_2_segment_display_select_3_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_4_0/sim/binary_2_segment_display_select_4_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_5_0/sim/binary_2_segment_display_select_5_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_display_select_6_0/sim/binary_2_segment_display_select_6_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/ipshared/29c2/src/Decoder7448.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_Decoder7448_0_0/sim/binary_2_segment_Decoder7448_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_Decoder7448_1_0/sim/binary_2_segment_Decoder7448_1_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_Decoder7448_2_1/sim/binary_2_segment_Decoder7448_2_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/src/binary_2_segment_Decoder7448_3_0/sim/binary_2_segment_Decoder7448_3_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ipshared/8590/sim/binary_2_segment.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_binary_2_segment_0_0_2/sim/Calculator_total_binary_2_segment_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/ipshared/7bd1/xup_xor2.srcs/sources_1/new/xup_xor2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_xor2_0_0/sim/Adder_1_xup_xor2_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/ipshared/f130/xup_nor2.srcs/sources_1/new/xup_nor2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_nor2_0_0/sim/Adder_1_xup_nor2_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_nor2_0_2/sim/Adder_1_xup_nor2_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_xor2_0_1/sim/Adder_1_xup_xor2_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_nor2_0_3/sim/Adder_1_xup_nor2_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/ipshared/3120/xup_nor3.srcs/sources_1/new/xup_nor3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/src/Adder_1_xup_nor3_0_0/sim/Adder_1_xup_nor3_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/ipshared/09cb/sim/Adder_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_1/sim/Adder_5_Adder_1_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_2/sim/Adder_5_Adder_1_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_3/sim/Adder_5_Adder_1_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_4/sim/Adder_5_Adder_1_0_4.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/src/Adder_5_Adder_1_0_5/sim/Adder_5_Adder_1_0_5.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/ipshared/ea9f/sim/Adder_5.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_Adder_5_0_0/sim/Signed_calculator_Adder_5_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_xup_xor2_0_0/sim/input_5_complementor_xup_xor2_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_xup_xor2_0_1/sim/input_5_complementor_xup_xor2_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_xup_xor2_0_2/sim/input_5_complementor_xup_xor2_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_xup_xor2_0_3/sim/input_5_complementor_xup_xor2_0_3.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_xup_xor2_0_4/sim/input_5_complementor_xup_xor2_0_4.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_Adder_1_0_0/sim/input_5_complementor_Adder_1_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_Adder_1_0_1/sim/input_5_complementor_Adder_1_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_Adder_1_1_0/sim/input_5_complementor_Adder_1_1_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_Adder_1_1_1/sim/input_5_complementor_Adder_1_1_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/src/input_5_complementor_Adder_1_3_0/sim/input_5_complementor_Adder_1_3_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/ipshared/2b43/sim/input_5_complementor.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_0/sim/Signed_calculator_input_5_complementor_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_1/sim/Signed_calculator_input_5_complementor_0_1.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/src/Signed_calculator_input_5_complementor_0_2/sim/Signed_calculator_input_5_complementor_0_2.v" \
    "$ref_dir/../../../bd/Calculator_total/ipshared/7d26/sim/Signed_calculator.v" \
    "$ref_dir/../../../bd/Calculator_total/ip/Calculator_total_Signed_calculator_0_0_3/sim/Calculator_total_Signed_calculator_0_0.v" \
    "$ref_dir/../../../bd/Calculator_total/sim/Calculator_total.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Calculator_total xil_defaultlib.glbl -o Calculator_total_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Calculator_total_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Calculator_total.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Calculator_total_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Calculator_total_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Calculator_total.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Calculator_total.sh [-help]\n\
Usage: Calculator_total.sh [-lib_map_path]\n\
Usage: Calculator_total.sh [-reset_run]\n\
Usage: Calculator_total.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
